In [1]:
#William Dahl
#ICSI 436
#HW 4
#March 12th, 2019
import numpy as np

#positive matrix
Xp = np.matrix([[4,2,2,3,4,6,3,8],
                [1,4,3,6,4,2,2,3],
                [0,1,1,0,-1,0,1,0]])

#negative matrix
Xn = np.matrix([[9,6,9,8,10],
                [10,8,5,7,8],
                [1,0,0,1,-1]])

#calculates the mean of a martix
def mean(X):
    return np.mean(X, axis=1)

#calculates the covarince matrix of a given matrix
def cov(X, m):
    return (X-m) * (X-m).getT()

#calcultes the scatter within matrix
def scatter_within(Cp, Cn):
    return Cp + Cn

#calculates the scatter between martix
def scatter_between(Mp, Mn):
    return (Mp - Mn) * (Mp - Mn).T

#gets the optimal projection vector
def LDA(Sw, Sb):
    #gest the eigen values and the egin vectors of Sw.ISb
    eig_vals, eig_vecs = np.linalg.eig(Sw.getI() * Sb)

    #sorts the eigen values from higest to lowest and the respectinve eigen vector
    eig_pairs = [(eig_vals[i], eig_vecs[:,i]) for i in range(len(eig_vals))]
    eig_pairs = sorted(eig_pairs, key=lambda k: k[0], reverse=True)
    
    #returns the eigeinvector ascoaiated with the highest eign value
    return eig_pairs[0][1]
    

Mp = mean(Xp)
print('mean of Xp:')
print(Mp, '\n')

Mn = mean(Xn)
print('mean of Xn:')
print(Mn, '\n')

Cp = cov(Xp, Mp)
print('Covarince matrix of Xp:')
print(Cp, '\n')

Cn = cov(Xn, Mn)
print('Covarince matrix of Xn:')
print(Cn, '\n')

Sw = scatter_within(Cp, Cn)
print('Scartter within matrix:')
print(Sw, '\n')

Sb = scatter_between(Mp, Mn)
print('Scatter between matrix:')
print(Sb, '\n')

v = LDA(Sw, Sb)
print('Optimal LDA projection Direction vector:')
print(v, '\n')

#gets the optimal projection vector for the classes
def mybLDA_train(Xp, Xn):
    Mp = mean(Xp)
    Mn = mean(Xn)
    Cp = cov(Xp, Mp)
    Cn = cov(Xn, Mn)
    Sw = scatter_within(Cp, Cn)
    Sb = scatter_between(Mp, Mn)
    return LDA(Sw, Sb)

#classifys new data using the projection vector
def mynLDA_classify(X, v):
    #holds the classes for each new data object in the data matrix
    r = list()
    for i in range(X.shape[1]):
        #calculates the 1D representation for the new data object along the projection vector
        y = v.T * X[:,i]
        #uses 7 as a threshold for classes
        if y <= 7:
            #if value is less than 7 the class is positive
            r.append(1)
        else:
            #if value is greater than 7 the class is negative
            r.append(-1)
            
    return r

#new data to be classified
X = np.matrix([[1.3, 2.4, 6.7, 2.2, 3.4, 3.2],
               [8.1, 7.6, 2.1, 1.1, 0.5, 7.4],
               [ -1,   2,   3,  -2,   0,   2]])

v = (mybLDA_train(Xp, Xn))

print("classes for each cloumn of data in X")
print(mynLDA_classify(X,v))

mean of Xp:
[[4.   ]
 [3.125]
 [0.25 ]] 

mean of Xn:
[[8.4]
 [7.6]
 [0.2]] 

Covarince matrix of Xp:
[[30.    -6.    -5.   ]
 [-6.    16.875 -1.25 ]
 [-5.    -1.25   3.5  ]] 

Covarince matrix of Xn:
[[ 9.2 -0.2 -1.4]
 [-0.2 13.2  1.4]
 [-1.4  1.4  2.8]] 

Scartter within matrix:
[[39.2   -6.2   -6.4  ]
 [-6.2   30.075  0.15 ]
 [-6.4    0.15   6.3  ]] 

Scatter between matrix:
[[ 1.9360000e+01  1.9690000e+01 -2.2000000e-01]
 [ 1.9690000e+01  2.0025625e+01 -2.2375000e-01]
 [-2.2000000e-01 -2.2375000e-01  2.5000000e-03]] 

Optimal LDA projection Direction vector:
[[0.56941154]
 [0.62283144]
 [0.53651793]] 

classes for each cloumn of data in X
[1, -1, 1, 1, 1, -1]
